### ISSUE TITLE
Add single option to exclude standard library completely

### ISSUE THREAD

**Issue by eric-nieuwland** [ronaldoussoren/modulegraph2#26]
In the current version one needs to exclude each package in the standard library separately.
Would be very welcome to be able to exclude the standard library more simply.

**Comment by ronaldoussoren** [comment]
What's your use case for excluding the entire standard library? I'm trying to keep the API of modulegraph2 fairly minimal.

Note that the following should work for excluding the standard library in Python 3.10 or later:

```python3
graph = modulegraph2.ModuleGraph(...)
graph.add_excludes(sys.stdlib_module_names)
```

In older versions you have to add the list of standard library names to you script because the ``sys`` attribute is not available.

**Comment by eric-nieuwland** [comment]
As a developer
I want to see the import graph of my own software, without standard library and possibly without installed packages
so I can analyse the import structure of my code as a support for refactoring.

And as I'm using this package through its command line interface I'd like the code snippet above available through the CLI.

**Comment by ronaldoussoren** [comment]
Closing this as my recent changeset adds an implementation for this.

**Comment by eric-nieuwland** [comment]
Yes, your version is so much cooler than my 10 minutes clutch!
